enum_discrim_align_threshold = 100
imports_layout = "HorizontalVertical"
inline_attribute_width = 100
imports_granularity = "Crate"
normalize_comments = true
reorder_impl_items = true
struct_field_align_threshold = 100
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true