[package]
name = "bindings"
version = "0.1.0"
authors = ["Jade Iqbal"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
windows = "0.17.2"

[build-dependencies]
windows = "0.17.2"
